# Form implementation generated from reading ui file 'ui/CreateAccount_form.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CreateAccount_form(object):
    def setupUi(self, CreateAccount_form):
        CreateAccount_form.setObjectName("CreateAccount_form")
        CreateAccount_form.resize(400, 300)
        self.label = QtWidgets.QLabel(parent=CreateAccount_form)
        self.label.setGeometry(QtCore.QRect(60, 0, 281, 111))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=CreateAccount_form)
        self.label_2.setGeometry(QtCore.QRect(10, 130, 198, 18))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=CreateAccount_form)
        self.label_3.setGeometry(QtCore.QRect(10, 190, 201, 18))
        self.label_3.setObjectName("label_3")
        self.CrearCuenta = QtWidgets.QPushButton(parent=CreateAccount_form)
        self.CrearCuenta.setGeometry(QtCore.QRect(300, 250, 80, 38))
        font = QtGui.QFont()
        font.setFamily("Cantarell")
        font.setPointSize(19)
        font.setBold(True)
        font.setItalic(False)
        self.CrearCuenta.setFont(font)
        self.CrearCuenta.setObjectName("CrearCuenta")
        self.CreateUsuario = QtWidgets.QLineEdit(parent=CreateAccount_form)
        self.CreateUsuario.setGeometry(QtCore.QRect(260, 130, 113, 26))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CreateUsuario.sizePolicy().hasHeightForWidth())
        self.CreateUsuario.setSizePolicy(sizePolicy)
        self.CreateUsuario.setObjectName("CreateUsuario")
        self.CreatePassword = QtWidgets.QLineEdit(parent=CreateAccount_form)
        self.CreatePassword.setGeometry(QtCore.QRect(260, 190, 113, 26))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CreatePassword.sizePolicy().hasHeightForWidth())
        self.CreatePassword.setSizePolicy(sizePolicy)
        self.CreatePassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.PasswordEchoOnEdit)
        self.CreatePassword.setObjectName("CreatePassword")

        self.retranslateUi(CreateAccount_form)
        QtCore.QMetaObject.connectSlotsByName(CreateAccount_form)

    def retranslateUi(self, CreateAccount_form):
        _translate = QtCore.QCoreApplication.translate
        CreateAccount_form.setWindowTitle(_translate("CreateAccount_form", "Form"))
        self.label.setText(_translate("CreateAccount_form", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:700;\">Bienvenido </span></p><p align=\"center\"><span style=\" font-size:18pt; font-weight:700;\"> Cree una cuenta por favor</span></p></body></html>"))
        self.label_2.setText(_translate("CreateAccount_form", "Ingrese un nombre de usuario"))
        self.label_3.setText(_translate("CreateAccount_form", "Ingrese una contraseña propia"))
        self.CrearCuenta.setText(_translate("CreateAccount_form", "Crear"))
